name = "Turbulox"
uuid = "25c03aae-1219-43c4-862d-5fc87f57ed09"
authors = ["Syver Døving Agdestein <syverda@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Adapt = "4"
FFTW = "1"
KernelAbstractions = "0.9"
Random = "1"
julia = "1"
